# Generated by Django 5.2.6 on 2025-09-24 13:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя курьера")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="RU", verbose_name="Телефон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курьер",
                "verbose_name_plural": "Курьеры",
            },
        ),
        migrations.CreateModel(
            name="Florist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя флориста")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region="RU",
                        verbose_name="Телефон",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Флорист",
                "verbose_name_plural": "Флористы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название цветка"),
                ),
            ],
            options={
                "verbose_name": "Цветок",
                "verbose_name_plural": "Цветы",
            },
        ),
        migrations.CreateModel(
            name="Occasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Повод")),
            ],
            options={
                "verbose_name": "Повод",
                "verbose_name_plural": "Поводы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название букета"),
                ),
                ("description", models.TextField(verbose_name="Описание букета")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Фотография букета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Букет",
                "verbose_name_plural": "Букеты",
            },
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=20, region="RU", verbose_name="Телефон клиента"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий клиента"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания заявки",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки заявки"
                    ),
                ),
                (
                    "florist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_requests",
                        to="core.florist",
                        verbose_name="Назначенный флорист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на консультацию",
                "verbose_name_plural": "Заявки на консультацию",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=50, verbose_name="Имя клиента"),
                ),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="RU", verbose_name="Телефон клиента"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email клиента"
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="Адрес доставки")),
                ("delivery_date", models.DateField(verbose_name="Дата доставки")),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий к заказу"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("paid", "Оплачен"),
                            ("assigned", "Передан курьеру"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время доставки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания заказа",
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.courier",
                        verbose_name="Курьер",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.product",
                        verbose_name="Букет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductFlowerComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.flower",
                        verbose_name="Цветок",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flower_composition",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав букета",
                "verbose_name_plural": "Составы букетов",
            },
        ),
        migrations.CreateModel(
            name="ProductOccasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Основной повод"),
                ),
                (
                    "occasion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.occasion",
                        verbose_name="Повод",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                        verbose_name="Букет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь букет-повод",
                "verbose_name_plural": "Связи букет-повод",
                "unique_together": {("product", "occasion")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="occasions",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="core.ProductOccasion",
                to="core.occasion",
                verbose_name="Поводы",
            ),
        ),
    ]
