# Generated by Django 5.2.6 on 2025-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('any', 'Как можно скорее'), ('10-12', '10:00 - 12:00'), ('12-14', '12:00 - 14:00'), ('14-16', '14:00 - 16:00'), ('16-18', '16:00 - 18:00'), ('18-20', '18:00 - 20:00')], default='any', max_length=20, verbose_name='Время доставки'),
        ),
    ]
