# Generated by Django 5.2.6 on 2025-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productflowercomposition',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='first_description',
        ),
        migrations.AddField(
            model_name='product',
            name='last_description',
            field=models.TextField(blank=True, null=True, verbose_name='Общее описание букета'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название цветка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='', verbose_name='Фотография букета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название букета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(related_name='products', through='core.ProductOccasion', to='core.occasion', verbose_name='Поводы'),
        ),
    ]
