services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend-collectstatic:
    build:
      context: ..
      dockerfile: ./flower_store/Dockerfile
      target: static
    env_file:
      - ../.env
    volumes:
      - ../flower_store/staticfiles:/app/flower_store/staticfiles
      - ../flower_store/static:/app/flower_store/static
    command: sh -lc "python manage.py collectstatic --noinput"
    restart: "no"

  backend-migrate:
    build:
      context: ..
      dockerfile: ./flower_store/Dockerfile
      target: migrate
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  web:
    build:
      context: ..
      dockerfile: ./flower_store/Dockerfile
      target: web-prod
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../flower_store/media:/app/flower_store/media:rw
      - ../flower_store/staticfiles:/app/flower_store/staticfiles:ro
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      gunicorn flower_store.wsgi:application
      --bind 0.0.0.0:8000
    depends_on:
      - db
      - backend-collectstatic
      - backend-migrate

